---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "README-"
)
options(width = 120L)
```

# Ruchardet

An R bindings of the [uchardet](https://www.freedesktop.org/wiki/Software/uchardet/) library. 

## Installation

To install the package from the CRAN run the following command:

```r
install.packages("Ruchardet", repos = "https://cloud.r-project.org/")
```

To install the development version from git repository the `install_github()` function from `devtools` package can be used:

```r
devtools::install_github('Ruchardet', 'haven-jeon')
```

## Usage

```{r example}
library(Ruchardet, quietly = TRUE)

nm <- '안녕하세요! 고감자입니다'
benc <- detectEncoding(nm)
benc
nme <- iconv(nm, benc, "CP949")
detectEncoding(c(nm, nme))

# Detection of unknown file encoding
tmp <- tempfile()
writeLines(nme, tmp)
detectFileEncoding(tmp)

# URL encoding detection 
detectFileEncoding('http://www.ppomppu.co.kr/')
detectFileEncoding('http://freesearch.pe.kr')
```

## Bug reports

Use the following command to go to the page for bug report submissions:

```r
bug.report(package = "benchr")
```
