# CMake generated Testfile for 
# Source directory: /home/xxx/projects/R/packages/Ruchardet/src/uchardet/test
# Build directory: /home/xxx/projects/R/packages/Ruchardet/src/uchardet/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ar:iso-8859-6 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ar/iso-8859-6.txt")
add_test(ar:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ar/utf-8.txt")
add_test(ar:windows-1256 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ar/windows-1256.txt")
add_test(bg:windows-1251 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/bg/windows-1251.txt")
add_test(da:iso-8859-15 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/da/iso-8859-15.txt")
add_test(da:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/da/utf-8.txt")
add_test(da:windows-1252 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/da/windows-1252.txt")
add_test(de:iso-8859-1 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/de/iso-8859-1.txt")
add_test(de:windows-1252 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/de/windows-1252.txt")
add_test(el:iso-8859-7 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/el/iso-8859-7.txt")
add_test(el:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/el/utf-8.txt")
add_test(el:windows-1253 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/el/windows-1253.txt")
add_test(en:ascii "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/en/ascii.txt")
add_test(eo:iso-8859-3 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/eo/iso-8859-3.txt")
add_test(es:iso-8859-1 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/es/iso-8859-1.txt")
add_test(es:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/es/utf-8.txt")
add_test(es:windows-1252 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/es/windows-1252.txt")
add_test(fr:iso-8859-1 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/fr/iso-8859-1.txt")
add_test(fr:iso-8859-15 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/fr/iso-8859-15.txt")
add_test(fr:utf-16 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/fr/utf-16.be")
add_test(fr:utf-32 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/fr/utf-32.le")
add_test(fr:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/fr/utf-8.txt")
add_test(fr:windows-1252 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/fr/windows-1252.txt")
add_test(he:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/he/utf-8.txt")
add_test(he:windows-1255 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/he/windows-1255.txt")
add_test(hu:iso-8859-2 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/hu/iso-8859-2.txt")
add_test(hu:windows-1250 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/hu/windows-1250.txt")
add_test(ja:euc-jp "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ja/euc-jp.txt")
add_test(ja:iso-2022-jp "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ja/iso-2022-jp.txt")
add_test(ja:shift_jis "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ja/shift_jis.txt")
add_test(ja:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ja/utf-8.txt")
add_test(ko:euc-kr "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ko/euc-kr.smi")
add_test(ko:iso-2022-kr "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ko/iso-2022-kr.txt")
add_test(ko:utf-16 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ko/utf-16.le")
add_test(ko:utf-32 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ko/utf-32.be")
add_test(ko:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ko/utf-8.txt")
add_test(ru:ibm855 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ru/ibm855.txt")
add_test(ru:ibm866 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ru/ibm866.txt")
add_test(ru:iso-8859-5 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ru/iso-8859-5.txt")
add_test(ru:koi8-r "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ru/koi8-r.txt")
add_test(ru:mac-cyrillic "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ru/mac-cyrillic.txt")
add_test(ru:windows-1251 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/ru/windows-1251.txt")
add_test(th:iso-8859-11 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/th/iso-8859-11.txt")
add_test(th:tis-620 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/th/tis-620.txt")
add_test(th:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/th/utf-8.txt")
add_test(tr:iso-8859-3 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/tr/iso-8859-3.txt")
add_test(tr:iso-8859-9 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/tr/iso-8859-9.txt")
add_test(vi:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/vi/utf-8.txt")
add_test(vi:viscii "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/vi/viscii.txt")
add_test(vi:windows-1258 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/vi/windows-1258.txt")
add_test(zh:big5 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/zh/big5.txt")
add_test(zh:euc-tw "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/zh/euc-tw.txt")
add_test(zh:gb18030 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/zh/gb18030.txt")
add_test(zh:utf-8 "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/uchardet-tests" "/home/xxx/projects/R/packages/Ruchardet/src/uchardet/test/zh/utf-8.txt")
