// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// detectEncoding
CharacterVector detectEncoding(const CharacterVector& str);
RcppExport SEXP _Ruchardet_detectEncoding(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(detectEncoding(str));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Ruchardet_detectEncoding", (DL_FUNC) &_Ruchardet_detectEncoding, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Ruchardet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
