# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Detect encoding of input string
#' @param str Character vector.
#' @return Character vector with encoding names. For the unknown encodings return NAs.
#' @references \url{https://www.freedesktop.org/wiki/Software/uchardet/}
#' @export
#' @useDynLib Ruchardet
#' @importFrom Rcpp sourceCpp
detectEncoding <- function(str) {
    .Call('_Ruchardet_detectEncoding', PACKAGE = 'Ruchardet', str)
}

